<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="CURA_TestSuiteCollection_001" time="15.534" tests="4" failures="0" errors="4">
   <testsuite name="CURA_TestSuite_Login_001" tests="1" failures="0" errors="1" time="9.838" skipped="0" timestamp="31-01-2024T17:27:26" hostname="preetham - localhost" id="Test Suites/CURA_TestSuites/CURA_TestSuite_Login_001">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_Login_001/20240131_172705"/>
         <property name="logFiles" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_Login_001/20240131_172705/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="preetham - localhost"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="9.1.0.212"/>
         <property name="browser" value="Chrome 121.0.6167.139"/>
         <property name="hostAddress" value="127.0.0.1"/>
         <property name="sessionId" value="7e36d39b51f0c89a91a4be10d9683ba0"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/TC_CURA_Login_001" time="9.706" classname="Test Cases/TC_CURA_Login_001" status="ERROR">
         <error type="ERROR" message="Test Cases/TC_CURA_Login_001 FAILED.&#xa;Reason:&#xa;java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'&#xa;	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)&#xa;	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)&#xa;	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)&#xa;	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)&#xa;	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)&#xa;	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)&#xa;	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)&#xa;	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)&#xa;	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;"/>
         <system-out><![CDATA[31-01-2024T17:27:26 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_Login_001: Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:26 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: Current window maximized

31-01-2024T17:27:26 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

31-01-2024T17:27:27 - [MESSAGE][INFO] - Starting 'Chrome (headless)' driver

31-01-2024T17:27:27 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

31-01-2024T17:27:29 - [MESSAGE][PASSED] - Browser is opened with url: ''

31-01-2024T17:27:29 - [TEST_STEP][PASSED] - navigateToUrl("https://katalon-demo-cura.herokuapp.com/"): Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:35 - [MESSAGE][PASSED] - Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:35 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

31-01-2024T17:27:35 - [MESSAGE][PASSED] - Current window maximized

31-01-2024T17:27:35 - [TEST_STEP][PASSED] - Start setup action : setupTestCase: Method 'setupTestCase' complete successfully

31-01-2024T17:27:35 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment")): Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Method 'setupTestCase' complete successfully

31-01-2024T17:27:36 - [TEST_STEP][ERROR] - setText(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/input_Username_username"), findTestData("DDT_Test Data/CURA_Login_InternalData").getValue("input_Username", 1)): Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:36 - [MESSAGE][ERROR] - Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:36 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: Browser is closed

31-01-2024T17:27:36 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[31-01-2024T17:27:26 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_Login_001: Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
      </testcase>
      <system-out><![CDATA[31-01-2024T17:27:26 - [TEST_SUITE][ERROR] - CURA_TestSuite_Login_001: Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-out>
      <system-err><![CDATA[31-01-2024T17:27:26 - [TEST_SUITE][ERROR] - CURA_TestSuite_Login_001: Test Cases/TC_CURA_Login_001 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Login_001.run(TC_CURA_Login_001:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702225686.run(TempTestSuite1706702225686.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
   </testsuite>
   <testsuite name="CURA_TestSuite_MakeAppointment_002" tests="1" failures="0" errors="1" time="6.057" skipped="0" timestamp="31-01-2024T17:27:30" hostname="preetham - localhost" id="Test Suites/CURA_TestSuites/CURA_TestSuite_MakeAppointment_002">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_MakeAppointment_002/20240131_172710"/>
         <property name="logFiles" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_MakeAppointment_002/20240131_172710/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="preetham - localhost"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="9.1.0.212"/>
         <property name="browser" value="Chrome 121.0.6167.139"/>
         <property name="hostAddress" value="127.0.0.1"/>
         <property name="sessionId" value="69525fc5b94cf94acf5a768b199bf310"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/TC_CURA_MakeAppointment_002" time="5.87" classname="Test Cases/TC_CURA_MakeAppointment_002" status="ERROR">
         <error type="ERROR" message="java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'&#xa;	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)&#xa;	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)&#xa;	at CURA_TestSuite_MakeAppointment_002.setupTestCase(CURA_TestSuite_MakeAppointment_002.groovy:53)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)&#xa;	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)&#xa;	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)&#xa;	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)&#xa;	at TempTestSuite1706702230591.run(TempTestSuite1706702230591.groovy:36)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;"/>
         <system-out><![CDATA[31-01-2024T17:27:30 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_MakeAppointment_002: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_MakeAppointment_002.setupTestCase(CURA_TestSuite_MakeAppointment_002.groovy:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702230591.run(TempTestSuite1706702230591.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:30 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: Current window maximized

31-01-2024T17:27:30 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

31-01-2024T17:27:31 - [MESSAGE][INFO] - Starting 'Chrome (headless)' driver

31-01-2024T17:27:31 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

31-01-2024T17:27:32 - [MESSAGE][PASSED] - Browser is opened with url: ''

31-01-2024T17:27:32 - [TEST_STEP][PASSED] - navigateToUrl("https://katalon-demo-cura.herokuapp.com/"): Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:34 - [MESSAGE][PASSED] - Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:34 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

31-01-2024T17:27:35 - [MESSAGE][PASSED] - Current window maximized

31-01-2024T17:27:35 - [TEST_STEP][ERROR] - Start setup action : setupTestCase: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'

31-01-2024T17:27:35 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment")): Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:36 - [TEST_STEP][PASSED] - setText(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/input_Username_username"), findTestData("DDT_Test Data/CURA_Login_InternalData").getValue("input_Username", 1)): null

31-01-2024T17:27:36 - [MESSAGE][ERROR] - Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'

31-01-2024T17:27:36 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: Browser is closed

31-01-2024T17:27:36 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[31-01-2024T17:27:30 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_MakeAppointment_002: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_MakeAppointment_002.setupTestCase(CURA_TestSuite_MakeAppointment_002.groovy:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702230591.run(TempTestSuite1706702230591.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
      </testcase>
      <system-out><![CDATA[31-01-2024T17:27:30 - [TEST_SUITE][ERROR] - CURA_TestSuite_MakeAppointment_002: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_MakeAppointment_002.setupTestCase(CURA_TestSuite_MakeAppointment_002.groovy:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702230591.run(TempTestSuite1706702230591.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-out>
      <system-err><![CDATA[31-01-2024T17:27:30 - [TEST_SUITE][ERROR] - CURA_TestSuite_MakeAppointment_002: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_MakeAppointment_002.setupTestCase(CURA_TestSuite_MakeAppointment_002.groovy:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702230591.run(TempTestSuite1706702230591.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
   </testsuite>
   <testsuite name="CURA_TestSuite_HistoryValidation_004" tests="1" failures="0" errors="1" time="7.218" skipped="0" timestamp="31-01-2024T17:27:34" hostname="preetham - localhost" id="Test Suites/CURA_TestSuites/CURA_TestSuite_HistoryValidation_004">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_HistoryValidation_004/20240131_172715"/>
         <property name="logFiles" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_HistoryValidation_004/20240131_172715/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="preetham - localhost"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="9.1.0.212"/>
         <property name="browser" value="Chrome 121.0.6167.139"/>
         <property name="hostAddress" value="127.0.0.1"/>
         <property name="sessionId" value="64d7dc48cb9688b2f5fb42a24712faa1"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/TC_CURA_HistoryValidation_004" time="6.915" classname="Test Cases/TC_CURA_HistoryValidation_004" status="ERROR">
         <error type="ERROR" message="java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'&#xa;	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)&#xa;	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)&#xa;	at CURA_TestSuite_HistoryValidation_004.setupTestCase(CURA_TestSuite_HistoryValidation_004.groovy:54)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)&#xa;	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)&#xa;	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)&#xa;	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)&#xa;	at TempTestSuite1706702235348.run(TempTestSuite1706702235348.groovy:36)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;"/>
         <system-out><![CDATA[31-01-2024T17:27:34 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_HistoryValidation_004: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_HistoryValidation_004.setupTestCase(CURA_TestSuite_HistoryValidation_004.groovy:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702235348.run(TempTestSuite1706702235348.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:34 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: Current window maximized

31-01-2024T17:27:34 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

31-01-2024T17:27:34 - [MESSAGE][INFO] - Starting 'Chrome (headless)' driver

31-01-2024T17:27:34 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

31-01-2024T17:27:36 - [MESSAGE][PASSED] - Browser is opened with url: ''

31-01-2024T17:27:36 - [TEST_STEP][PASSED] - navigateToUrl("https://katalon-demo-cura.herokuapp.com/"): Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:39 - [MESSAGE][PASSED] - Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:40 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

31-01-2024T17:27:40 - [MESSAGE][PASSED] - Current window maximized

31-01-2024T17:27:40 - [TEST_STEP][ERROR] - Start setup action : setupTestCase: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'

31-01-2024T17:27:40 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment")): Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:41 - [MESSAGE][PASSED] - Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:41 - [TEST_STEP][PASSED] - setText(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/input_Username_username"), findTestData("DDT_Test Data/CURA_Login_InternalData").getValue("input_Username", 1)): null

31-01-2024T17:27:41 - [MESSAGE][ERROR] - Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'

31-01-2024T17:27:41 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: Browser is closed

31-01-2024T17:27:41 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

31-01-2024T17:27:41 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[31-01-2024T17:27:34 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_HistoryValidation_004: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_HistoryValidation_004.setupTestCase(CURA_TestSuite_HistoryValidation_004.groovy:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702235348.run(TempTestSuite1706702235348.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
      </testcase>
      <system-out><![CDATA[31-01-2024T17:27:34 - [TEST_SUITE][ERROR] - CURA_TestSuite_HistoryValidation_004: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_HistoryValidation_004.setupTestCase(CURA_TestSuite_HistoryValidation_004.groovy:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702235348.run(TempTestSuite1706702235348.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-out>
      <system-err><![CDATA[31-01-2024T17:27:34 - [TEST_SUITE][ERROR] - CURA_TestSuite_HistoryValidation_004: java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at CURA_TestSuite_HistoryValidation_004.setupTestCase(CURA_TestSuite_HistoryValidation_004.groovy:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:223)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:201)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeEachTestCaseMethod(TestSuiteExecutor.java:185)
	at com.kms.katalon.core.main.TestCaseExecutor.invokeTestSuiteMethod(TestCaseExecutor.java:381)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:276)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702235348.run(TempTestSuite1706702235348.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
   </testsuite>
   <testsuite name="CURA_TestSuite_Logout_005" tests="1" failures="0" errors="1" time="5.395" skipped="0" timestamp="31-01-2024T17:27:38" hostname="preetham - localhost" id="Test Suites/CURA_TestSuites/CURA_TestSuite_Logout_005">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_Logout_005/20240131_172720"/>
         <property name="logFiles" value="/Users/preetham/git/SI-GuidedProject-705189-1706291116/Reports/20240131_172700/CURA_TestSuites/CURA_TestSuite_Logout_005/20240131_172720/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="preetham - localhost"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="9.1.0.212"/>
         <property name="browser" value="Chrome 121.0.6167.139"/>
         <property name="hostAddress" value="127.0.0.1"/>
         <property name="sessionId" value="0a514a88a5ed9bc7328178dea29d36c0"/>
         <property name="seleniumVersion" value="3.141.59"/>
         <property name="proxyInformation" value="ProxyInformation { proxyOption=NO_PROXY, proxyServerType=HTTP, username=, password=********, proxyServerAddress=, proxyServerPort=0, executionList=&quot;&quot;, isApplyToDesiredCapabilities=true }"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/TC_CURA_Logout_005" time="5.263" classname="Test Cases/TC_CURA_Logout_005" status="ERROR">
         <error type="ERROR" message="Test Cases/TC_CURA_Logout_005 FAILED.&#xa;Reason:&#xa;java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'&#xa;	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)&#xa;	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)&#xa;	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)&#xa;	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)&#xa;	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)&#xa;	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)&#xa;	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)&#xa;	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)&#xa;	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)&#xa;	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)&#xa;	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xa;	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#xa;	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xa;"/>
         <system-out><![CDATA[31-01-2024T17:27:38 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_Logout_005: Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:39 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: Current window maximized

31-01-2024T17:27:39 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

31-01-2024T17:27:39 - [MESSAGE][INFO] - Starting 'Chrome (headless)' driver

31-01-2024T17:27:39 - [MESSAGE][INFO] - Action delay is set to 0 milliseconds

31-01-2024T17:27:40 - [MESSAGE][PASSED] - Browser is opened with url: ''

31-01-2024T17:27:40 - [TEST_STEP][PASSED] - navigateToUrl("https://katalon-demo-cura.herokuapp.com/"): Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:43 - [MESSAGE][PASSED] - Navigate to 'https://katalon-demo-cura.herokuapp.com/' successfully

31-01-2024T17:27:43 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

31-01-2024T17:27:43 - [MESSAGE][PASSED] - Current window maximized

31-01-2024T17:27:43 - [TEST_STEP][PASSED] - click(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment")): Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:44 - [MESSAGE][PASSED] - Object: 'Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/a_Make Appointment' is clicked on

31-01-2024T17:27:44 - [TEST_STEP][ERROR] - setText(findTestObject("Object Repository/CURA_Pages_OR/Page_CURA Healthcare Service/input_Username_username"), findTestData("DDT_Test Data/CURA_Login_InternalData").getValue("input_Username", 1)): Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:44 - [MESSAGE][ERROR] - Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


31-01-2024T17:27:44 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: Browser is closed

31-01-2024T17:27:44 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

31-01-2024T17:27:44 - [MESSAGE][PASSED] - Browser is closed]]></system-out>
         <system-err><![CDATA[31-01-2024T17:27:38 - [TEST_CASE][ERROR] - Test Cases/TC_CURA_Logout_005: Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
      </testcase>
      <system-out><![CDATA[31-01-2024T17:27:38 - [TEST_SUITE][ERROR] - CURA_TestSuite_Logout_005: Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-out>
      <system-err><![CDATA[31-01-2024T17:27:38 - [TEST_SUITE][ERROR] - CURA_TestSuite_Logout_005: Test Cases/TC_CURA_Logout_005 FAILED.
Reason:
java.lang.IllegalArgumentException: Cannot find test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' because (of) 'java.lang.IllegalArgumentException: Test data with id 'Data Files/DDT_Test Data/CURA_Login_InternalData' does not exist'
	at com.kms.katalon.core.testdata.TestDataFactory.findTestData(TestDataFactory.java:132)
	at com.kms.katalon.core.testdata.TestDataFactory$findTestData.callStatic(Unknown Source)
	at TC_CURA_Logout_005.run(TC_CURA_Logout_005:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.common.CommonExecutor.accessTestCaseMainPhase(CommonExecutor.java:65)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:148)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:180)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1706702240139.run(TempTestSuite1706702240139.groovy:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)]]></system-err>
   </testsuite>
</testsuites>
